-- Payment verification columns (run once)
ALTER TABLE orders ADD COLUMN IF NOT EXISTS transaction_id VARCHAR(50) DEFAULT NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS upi_payer_name VARCHAR(255) DEFAULT NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS amount_entered DECIMAL(10,2) DEFAULT NULL;
